# **Ejemplos de matrices Dispersas (sparse matrices)**

https://docs.scipy.org/doc/scipy/reference/sparse.html

In [ ]:
import numpy as np
from scipy import sparse

In [ ]:
A = np.array([[0, 0, 9, 0, 3, 0], [0, 0, 7, 0, 0, 0],
              [0, -1, 0, 0, 0, 4], [2, 6, 0, 8, 0, 0]], dtype=np.int64)

A    # representación densa.

array([[ 0,  0,  9,  0,  3,  0],
       [ 0,  0,  7,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  4],
       [ 2,  6,  0,  8,  0,  0]])

#**Ejemplo CSR: Compressed Sparse Row**

In [ ]:
B = sparse.csr_matrix(A)     # transformación a una representación dispersa (sparse).

B

<4x6 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [ ]:
print(B)

  (0, 2)	9
  (0, 4)	3
  (1, 2)	7
  (2, 1)	-1
  (2, 5)	4
  (3, 0)	2
  (3, 1)	6
  (3, 3)	8


In [ ]:
# Simple-triplet-matrix representation:

print(B.indptr)
print(B.indices)
print(B.data)

[0 2 3 5 8]
[2 4 2 1 5 0 1 3]
[ 9  3  7 -1  4  2  6  8]


In [ ]:
# Podemos obtener las coordenadas de los valores no cero:
rows, cols = B.nonzero()
print(rows)
print(cols)

[0 0 1 2 2 3 3 3]
[2 4 2 1 5 0 1 3]


In [ ]:
print(B.data)   # también los valores no cero, solamente.

[ 9  3  7 -1  4  2  6  8]


In [ ]:
# Podemos llevar a cabo operaciones de matrices de la manera usual.
# Por ejemplo, si queremos encontrar el producto de B con su
# traspuesta lo hacemos de la manera estándar de multiplicación
# de matrices, e internamente la librería SciPy se encarga de
# llevar a cabo dicha operación:

F = B @ B.T
F   # observa que de manera predeterminada no se despliega la información del producto.

<4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [ ]:
F.todense()   # Si deseas visualizar el resultado y ver toda la matriz.

matrix([[ 90,  63,   0,   0],
        [ 63,  49,   0,   0],
        [  0,   0,  17,  -6],
        [  0,   0,  -6, 104]])

In [ ]:
F.toarray()   # también podemos hacerla densa de esta otra forma.
              # Por cierto, este resultado nos lleva a las llamadas matrices por bloques.

array([[ 90,  63,   0,   0],
       [ 63,  49,   0,   0],
       [  0,   0,  17,  -6],
       [  0,   0,  -6, 104]])

#### **Pero recuerda, solamente para casos sencillos despliega la matriz en su forma densa, porque de lo contrario puedes tener problemas de recursos de memoria.**

In [ ]:
# Si deseas determinar la cantidad de valores no cero que tiene una matriz:
np.count_nonzero(A)

8

In [ ]:
A.size   # Y si deseas la cantidad de entradas que tiene una matriz: num_rows * num_cols

24

In [ ]:
# Con dichos valores puedes encontrar la cantidad de valores cero de la matriz (sparcity):
sparsity = 1 - np.count_nonzero(A) / A.size
sparsity

0.6666666666666667

#**Ejemplo CSC: Compressed Sparse Column**

In [ ]:
C = np.array([[0, 0, 9, 0, 0, 0], [0, 0, 0, 0, 0, 0],
              [0, -1, 7, 0, 0, 4], [2, 6, 0, 0, 0, 0]], dtype=np.int64)
C

array([[ 0,  0,  9,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0, -1,  7,  0,  0,  4],
       [ 2,  6,  0,  0,  0,  0]])

In [ ]:
D = sparse.csc_matrix(C)

D

<4x6 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Column format>

In [ ]:
print(D)

  (3, 0)	2
  (2, 1)	-1
  (3, 1)	6
  (0, 2)	9
  (2, 2)	7
  (2, 5)	4


In [ ]:
print(D.indptr)
print(D.indices)
print(D.data)

[0 1 3 5 5 5 6]
[3 2 3 0 2 2]
[ 2 -1  6  9  7  4]


#**Ejemplo COO: Coordinate format**

In [ ]:
print(A)

[[ 0  0  9  0  3  0]
 [ 0  0  7  0  0  0]
 [ 0 -1  0  0  0  4]
 [ 2  6  0  8  0  0]]


In [ ]:
D = sparse.coo_matrix(A, dtype=np.int8)
print(D)   # ijv format - triplet format

  (0, 2)	9
  (0, 4)	3
  (1, 2)	7
  (2, 1)	-1
  (2, 5)	4
  (3, 0)	2
  (3, 1)	6
  (3, 3)	8


In [ ]:
print(D.row)
print(D.col)
print(D.data)


[0 0 1 2 2 3 3 3]
[2 4 2 1 5 0 1 3]
[ 9  3  7 -1  4  2  6  8]
